const seasons = {
	Spring: {
		id: 1,
		name: "Spring",
		image: "Spring.png",
		weather: ["Sun", "Rain", "Wind"],
	},
	Summer: {
		id: 2,
		name: "Summer",
		image: "Summer.png",
		weather: ["Sun", "Rain"],
	},
	Fall: {
		id: 3,
		name: "Fall",
		image: "Fall.png",
		weather: ["Sun", "Rain", "Wind"],
	},
	Winter: {
		id: 4,
		name: "Winter",
		image: "Winter.png",
		weather: ["Sun", "Snow", "Rain"],
	},
};
exports.seasons = seasons;
exports.seasonsNames = Object.keys(seasons);

const weather = {
	Sun: {
		name: "Sun",
		shortName: "Su",
		type: 1,
		images: {
			Spring: "StatusSun.png",
			Summer: "StatusSun.png",
			Fall: "StatusSun.png",
			Winter: "StatusSun.png",
		},
	},
	Rain: {
		name: "Rain",
		shortName: "Rn",
		type: 2,
		images: {
			Spring: "StatusRain.png",
			Summer: "StatusRain.png",
			Fall: "StatusRain.png",
			Winter: "StatusRain.png",
		},
	},
	Snow: {
		name: "Snow",
		shortName: "Sw",
		type: 2,
		images: {
			Winter: "StatusSnow.png",
		},
	},
	Wind: {
		name: "Wind",
		shortName: "Wd",
		type: 4,
		images: {
			Spring: "StatusWindSpring.png",
			Fall: "StatusWindFall.png",
		},
	},
};
exports.weather = weather;
exports.weatherNames = Object.keys(weather);

const locationTown = {
	Ocean: {
		name: "Ocean",
		locationGroup: "Town",
		mapLocation: "Ocean",
		waterSalinity: "Salt",
		waterStillness: "Ocean",
		legendLocation: "North of JojaMart",
	},
	"Town River": {
		name: "Town River",
		locationGroup: "Town",
		mapLocation: "Town",
		waterSalinity: "Fresh",
		waterStillness: "River",
		legendLocation: "North of JojaMart",
	},
	"Mountain Lake": {
		name: "Mountain Lake",
		locationGroup: "Town",
		mapLocation: "Mountain",
		waterSalinity: "Fresh",
		waterStillness: "Lake",
		legendLocation: "On Island near Log",
	},
	"Forrest River": {
		name: "Forrest River",
		locationGroup: "Town",
		mapLocation: "Forrest",
		waterSalinity: "Fresh",
		waterStillness: "River",
		legendLocation: "South end of Arrowhead Island",
	},
	"Forrest Pond": {
		name: "Forrest Pond",
		locationGroup: "Town",
		mapLocation: "Forrest",
		waterSalinity: "Fresh",
		waterStillness: "Lake",
	},
};
const locationSpecial = {
	"Night Market": {
		name: "Night Market",
		locationGroup: "Special",
		mapLocation: "Night Market",
	},
	"Secret Woods Pond": {
		name: "Secret Woods Pond",
		locationGroup: "Special",
		mapLocation: "Secret Woods",
	},
	Desert: {
		name: "Desert",
		locationGroup: "Special",
		mapLocation: "Desert",
	},
	Mines: {
		name: "Mines",
		locationGroup: "Special",
		mapLocation: "Mines",
	},
	Sewers: {
		name: "Sewers",
		locationGroup: "Special",
		mapLocation: "Sewers",
	},
	"Mutant Bug Lair": {
		name: "Mutant Bug Lair",
		locationGroup: "Special",
		mapLocation: "Sewers",
	},
	"Witch Swamp": {
		name: "Witch Swamp",
		locationGroup: "Special",
		mapLocation: "Swamp",
	},
};
const locationFarm = {
	"Farm Pond": {
		name: "Farm Pond",
		locationGroup: "Farm",
		mapLocation: "Farm",
	},
	"Forrest Pond": {
		name: "Forrest Pond",
		locationGroup: "Farm",
		mapLocation: "Farm",
	},
};

const locations = {
	locationTown: locationTown,
	locationSpecial: locationSpecial,
	locationFarm: locationFarm,
};
exports.locations = locations;

const fish = [
	{
		name: "Crimsonfish",
		id: 29,
		desc: "Lives deep in the ocean but likes to lay its eggs in the warm summer water.",
		type: "Legendary",
		legend: true,
		price: [1500, 1875, 2250, 3000],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer"],
		weather: ["Sun", "Rain"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 95, behavior: "mixed" },
		size: { min: 19, max: 21 },
		tool: "Fishing Pole",
		baseXP: 170,
		fishPond: false,
		cooking: false,
	},
	{
		name: "Angler",
		id: 30,
		desc: "Uses a bioluminescent dangler to attract prey.",
		type: "Legendary",
		legend: true,
		price: [900, 1125, 1350, 1800],
		locationTown: ["Town River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Fall"],
		weather: ["Sun", "Rain"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 85, behavior: "smooth" },
		size: { min: 17, max: 19 },
		tool: "Fishing Pole",
		baseXP: 155,
		fishPond: false,
		cooking: false,
	},
	{
		name: "Legend",
		id: 33,
		desc: "The king of all fish! They said he'd never be caught.",
		type: "Legendary",
		legend: true,
		price: [5000, 6250, 7500, 10000],
		locationTown: ["Mountain Lake"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring"],
		weather: ["Rain"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 110, behavior: "mixed" },
		size: { min: 49, max: 51 },
		tool: "Fishing Pole",
		baseXP: 195,
		fishPond: false,
		cooking: false,
	},
	{
		name: "Mutant Carp",
		id: 36,
		desc: "The strange waters of the sewer turned this carp into a monstrosity.",
		type: "Legendary",
		legend: true,
		price: [1000, 1250, 1500, 2000],
		locationTown: [],
		locationSpecial: ["Sewers"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Rain"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 80, behavior: "dart" },
		size: { min: 35, max: 37 },
		tool: "Fishing Pole",
		baseXP: 145,
		fishPond: false,
		cooking: false,
	},
	{
		name: "Glacierfish",
		id: 57,
		desc: "Builds a nest on the underside of glaciers.",
		type: "Legendary",
		legend: true,
		price: [1000, 1250, 1500, 2000],
		locationTown: ["Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Winter"],
		weather: ["Sun", "Rain"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 100, behavior: "mixed" },
		size: { min: 26, max: 28 },
		tool: "Fishing Pole",
		baseXP: 180,
		fishPond: false,
		cooking: false,
	},
	{
		name: "Pufferfish",
		id: 1,
		desc: "Inflates when threatened.",
		type: "Regular",
		legend: false,
		price: [200, 250, 300, 400],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer"],
		weather: ["Sun"],
		times: [{ start: 12, end: 16 }],
		behavior: { difficulty: 80, behavior: "floater" },
		size: { min: 1, max: 37 },
		tool: "Fishing Pole",
		baseXP: 29,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Anchovy",
		id: 2,
		desc: "A small silver fish found in the ocean.",
		type: "Regular",
		legend: false,
		price: [30, 37, 45, 60],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Fall"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 30, behavior: "dart" },
		size: { min: 1, max: 17 },
		tool: "Fishing Pole",
		baseXP: 13,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Tuna",
		id: 3,
		desc: "A large fish that lives in the ocean.",
		type: "Regular",
		legend: false,
		price: [100, 125, 150, 200],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 70, behavior: "smooth" },
		size: { min: 12, max: 61 },
		tool: "Fishing Pole",
		baseXP: 26,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Sardine",
		id: 4,
		desc: "A common ocean fish.",
		type: "Regular",
		legend: false,
		price: [40, 50, 60, 80],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Fall"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 30, behavior: "dart" },
		size: { min: 1, max: 13 },
		tool: "Fishing Pole",
		baseXP: 13,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Bream",
		id: 5,
		desc: "A fairly common river fish that becomes active at night.",
		type: "Regular",
		legend: false,
		price: [45, 56, 67, 90],
		locationTown: ["Town River", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 18, end: 26 }],
		behavior: { difficulty: 35, behavior: "smooth" },
		size: { min: 12, max: 31 },
		tool: "Fishing Pole",
		baseXP: 14,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Largemouth Bass",
		id: 6,
		desc: "A popular fish that lives in lakes.",
		type: "Regular",
		legend: false,
		price: [100, 125, 150, 200],
		locationTown: ["Mountain Lake"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 50, behavior: "mixed" },
		size: { min: 11, max: 31 },
		tool: "Fishing Pole",
		baseXP: 19,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Smallmouth Bass",
		id: 7,
		desc: "A freshwater fish that is very sensitive to pollution.",
		type: "Regular",
		legend: false,
		price: [50, 62, 75, 100],
		locationTown: ["Forrest River", "Forrest Pond"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Fall"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 28, behavior: "mixed" },
		size: { min: 12, max: 25 },
		tool: "Fishing Pole",
		baseXP: 12,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Rainbow Trout",
		id: 8,
		desc: "A freshwater trout with colorful markings.",
		type: "Regular",
		legend: false,
		price: [65, 81, 97, 130],
		locationTown: ["Mountain Lake", "Town River", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer"],
		weather: ["Sun"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 45, behavior: "mixed" },
		size: { min: 10, max: 26 },
		tool: "Fishing Pole",
		baseXP: 18,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Salmon",
		id: 9,
		desc: "Swims upstream to lay its eggs.",
		type: "Regular",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: ["Town River", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Fall"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 50, behavior: "mixed" },
		size: { min: 24, max: 66 },
		tool: "Fishing Pole",
		baseXP: 19,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Walleye",
		id: 10,
		desc: "A freshwater fish caught at night.",
		type: "Regular",
		legend: false,
		price: [105, 131, 157, 210],
		locationTown: [
			"Mountain Lake",
			"Town River",
			"Forrest River",
			"Forrest Pond",
		],
		locationSpecial: [],
		locationFarm: [],
		season: ["Fall", "Winter"],
		weather: ["Rain"],
		times: [{ start: 12, end: 26 }],
		behavior: { difficulty: 45, behavior: "smooth" },
		size: { min: 10, max: 41 },
		tool: "Fishing Pole",
		baseXP: 18,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Perch",
		id: 11,
		desc: "A freshwater fish of the winter.",
		type: "Regular",
		legend: false,
		price: [55, 68, 82, 110],
		locationTown: [
			"Mountain Lake",
			"Town River",
			"Forrest River",
			"Forrest Pond",
		],
		locationSpecial: [],
		locationFarm: [],
		season: ["Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 35, behavior: "dart" },
		size: { min: 10, max: 25 },
		tool: "Fishing Pole",
		baseXP: 14,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Carp",
		id: 12,
		desc: "A common pond fish.",
		type: "Regular",
		legend: false,
		price: [30, 37, 45, 60],
		locationTown: ["Mountain Lake"],
		locationSpecial: ["Secret Woods Pond", "Sewers"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 15, behavior: "mixed" },
		size: { min: 15, max: 51 },
		tool: "Fishing Pole",
		baseXP: 8,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Catfish",
		id: 13,
		desc: "An uncommon fish found in streams.",
		type: "Regular",
		legend: false,
		price: [200, 250, 300, 400],
		locationTown: ["Town River", "Forrest River"],
		locationSpecial: ["Secret Woods Pond", "Witch Swamp"],
		locationFarm: [],
		season: ["Spring", "Fall", "Winter"],
		weather: ["Rain"],
		times: [{ start: 6, end: 24 }],
		behavior: { difficulty: 75, behavior: "mixed" },
		size: { min: 12, max: 73 },
		tool: "Fishing Pole",
		baseXP: 28,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Pike",
		id: 14,
		desc: "A freshwater fish that's difficult to catch.",
		type: "Regular",
		legend: false,
		price: [100, 125, 150, 200],
		locationTown: [
			"Mountain Lake",
			"Town River",
			"Forrest River",
			"Forrest Pond",
		],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 60, behavior: "dart" },
		size: { min: 15, max: 61 },
		tool: "Fishing Pole",
		baseXP: 23,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Sunfish",
		id: 15,
		desc: "A common river fish.",
		type: "Regular",
		legend: false,
		price: [30, 37, 45, 60],
		locationTown: ["Town River", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer"],
		weather: ["Sun", "Wind"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 30, behavior: "mixed" },
		size: { min: 5, max: 16 },
		tool: "Fishing Pole",
		baseXP: 13,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Red Mullet",
		id: 16,
		desc: "Long ago these were kept as pets.",
		type: "Regular",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 55, behavior: "smooth" },
		size: { min: 8, max: 23 },
		tool: "Fishing Pole",
		baseXP: 21,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Herring",
		id: 17,
		desc: "A common ocean fish.",
		type: "Regular",
		legend: false,
		price: [30, 37, 45, 60],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 25, behavior: "dart" },
		size: { min: 8, max: 21 },
		tool: "Fishing Pole",
		baseXP: 11,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Eel",
		id: 18,
		desc: "A long, slippery little fish.",
		type: "Regular",
		legend: false,
		price: [85, 106, 127, 170],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Fall"],
		weather: ["Rain"],
		times: [{ start: 16, end: 26 }],
		behavior: { difficulty: 70, behavior: "smooth" },
		size: { min: 12, max: 81 },
		tool: "Fishing Pole",
		baseXP: 26,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Octopus",
		id: 19,
		desc: "A mysterious and intelligent creature.",
		type: "Regular",
		legend: false,
		price: [150, 187, 225, 300],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 13 }],
		behavior: { difficulty: 95, behavior: "sinker" },
		size: { min: 12, max: 49 },
		tool: "Fishing Pole",
		baseXP: 34,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Red Snapper",
		id: 20,
		desc: "A popular fish with a nice red color.",
		type: "Regular",
		legend: false,
		price: [50, 62, 75, 100],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer", "Fall", "Winter"],
		weather: ["Rain"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 40, behavior: "mixed" },
		size: { min: 8, max: 26 },
		tool: "Fishing Pole",
		baseXP: 16,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Squid",
		id: 21,
		desc: "A deep sea creature that can grow to enormous size.",
		type: "Regular",
		legend: false,
		price: [80, 100, 120, 160],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 18, end: 26 }],
		behavior: { difficulty: 75, behavior: "sinker" },
		size: { min: 12, max: 49 },
		tool: "Fishing Pole",
		baseXP: 28,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Seaweed",
		id: 22,
		desc: "",
		type: "Regular",
		legend: false,
		price: [20, 25, 30, 35],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Fishing Pole",
		baseXP: 5,
		fishPond: false,
		cooking: false,
	},
	{
		name: "Green Algae",
		id: 23,
		desc: "",
		type: "Regular",
		legend: false,
		price: [15, 15, 15, 15],
		locationTown: [
			"Ocean",
			"Mountain Lake",
			"Town River",
			"Forrest River",
			"Forrest Pond",
		],
		locationSpecial: [
			"Night Market",
			"Secret Woods Pond",
			"Desert",
			"Mines",
			"Sewers",
			"Mutant Bug Lair",
			"Witch Swamp",
		],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Fishing Pole",
		baseXP: 5,
		fishPond: false,
		cooking: true,
	},
	{
		name: "Sea Cucumber",
		id: 24,
		desc: "A slippery, slimy creature found on the ocean floor.",
		type: "Regular",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 40, behavior: "sinker" },
		size: { min: 3, max: 21 },
		tool: "Fishing Pole",
		baseXP: 16,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Super Cucumber",
		id: 25,
		desc: "A rare, purple variety of sea cucumber.",
		type: "Regular",
		legend: false,
		price: [250, 312, 375, 500],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer", "Fall"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 18, end: 26 }],
		behavior: { difficulty: 80, behavior: "sinker" },
		size: { min: 12, max: 37 },
		tool: "Fishing Pole",
		baseXP: 29,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Ghostfish",
		id: 26,
		desc: "A pale, blind fish found in underground lakes.",
		type: "Special",
		legend: false,
		price: [45, 56, 67, 90],
		locationTown: [],
		locationSpecial: ["Mines"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 50, behavior: "mixed" },
		size: { min: 10, max: 36 },
		tool: "Fishing Pole",
		baseXP: 19,
		fishPond: true,
		cooking: false,
	},
	{
		name: "White Algae",
		id: 27,
		desc: "",
		type: "Special",
		legend: false,
		price: [25, 25, 25, 25],
		locationTown: [],
		locationSpecial: ["Mines", "Sewers", "Mutant Bug Lair", "Witch Swamp"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Fishing Pole",
		baseXP: 5,
		fishPond: false,
		cooking: true,
	},
	{
		name: "Stonefish",
		id: 28,
		desc: "A bizarre fish that's shaped like a brick.",
		type: "Special",
		legend: false,
		price: [300, 375, 450, 600],
		locationTown: [],
		locationSpecial: ["Mines"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 65, behavior: "sinker" },
		size: { min: 14, max: 16 },
		tool: "Fishing Pole",
		baseXP: 24,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Ice Pip",
		id: 31,
		desc: "A rare fish that thrives in extremely cold conditions.",
		type: "Special",
		legend: false,
		price: [500, 625, 750, 1000],
		locationTown: [],
		locationSpecial: ["Mines"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 85, behavior: "dart" },
		size: { min: 7, max: 9 },
		tool: "Fishing Pole",
		baseXP: 31,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Lava Eel",
		id: 32,
		desc: "It can somehow survive in pools of red-hot lava.",
		type: "Special",
		legend: false,
		price: [700, 875, 1050, 1400],
		locationTown: [],
		locationSpecial: ["Mines"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 90, behavior: "mixed" },
		size: { min: 31, max: 33 },
		tool: "Fishing Pole",
		baseXP: 33,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Sandfish",
		id: 34,
		desc: "It tries to hide using camouflage.",
		type: "Special",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: [],
		locationSpecial: ["Desert"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 20 }],
		behavior: { difficulty: 65, behavior: "mixed" },
		size: { min: 8, max: 25 },
		tool: "Fishing Pole",
		baseXP: 24,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Scorpion Carp",
		id: 35,
		desc: "It's like a regular carp but with a sharp stinger.",
		type: "Special",
		legend: false,
		price: [150, 187, 225, 300],
		locationTown: [],
		locationSpecial: ["Desert"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 20 }],
		behavior: { difficulty: 90, behavior: "dart" },
		size: { min: 12, max: 33 },
		tool: "Fishing Pole",
		baseXP: 33,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Sturgeon",
		id: 37,
		desc: "An ancient bottom-feeder with a dwindling population. Females can live up to 150 years.",
		type: "Regular",
		legend: false,
		price: [200, 250, 300, 400],
		locationTown: ["Mountain Lake"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 78, behavior: "mixed" },
		size: { min: 12, max: 61 },
		tool: "Fishing Pole",
		baseXP: 29,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Tiger Trout",
		id: 38,
		desc: "A rare hybrid trout that cannot bear offspring of its own.",
		type: "Regular",
		legend: false,
		price: [150, 187, 225, 300],
		locationTown: ["Town River", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 60, behavior: "dart" },
		size: { min: 10, max: 21 },
		tool: "Fishing Pole",
		baseXP: 23,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Bullhead",
		id: 39,
		desc: "A relative of the catfish that eats a variety of foods off the lake bottom.",
		type: "Regular",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: ["Mountain Lake"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 46, behavior: "smooth" },
		size: { min: 12, max: 31 },
		tool: "Fishing Pole",
		baseXP: 18,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Tilapia",
		id: 40,
		desc: "A primarily vegetarian fish that prefers warm water.",
		type: "Regular",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer", "Fall"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 14 }],
		behavior: { difficulty: 50, behavior: "mixed" },
		size: { min: 11, max: 31 },
		tool: "Fishing Pole",
		baseXP: 19,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Chub",
		id: 41,
		desc: "A common freshwater fish known for its voracious appetite.",
		type: "Regular",
		legend: false,
		price: [50, 62, 75, 100],
		locationTown: ["Mountain Lake", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 35, behavior: "dart" },
		size: { min: 12, max: 25 },
		tool: "Fishing Pole",
		baseXP: 14,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Dorado",
		id: 42,
		desc: "A fierce carnivore with brilliant orange scales.",
		type: "Regular",
		legend: false,
		price: [100, 125, 150, 200],
		locationTown: ["Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Summer"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 19 }],
		behavior: { difficulty: 78, behavior: "mixed" },
		size: { min: 24, max: 33 },
		tool: "Fishing Pole",
		baseXP: 29,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Albacore",
		id: 43,
		desc: 'Prefers temperature ""edges"" where cool and warm water meet.',
		type: "Regular",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [
			{ start: 6, end: 11 },
			{ start: 18, end: 2 },
		],
		behavior: { difficulty: 60, behavior: "mixed" },
		size: { min: 20, max: 41 },
		tool: "Fishing Pole",
		baseXP: 23,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Shad",
		id: 44,
		desc: "Lives in a school at sea, but returns to the rivers to spawn.",
		type: "Regular",
		legend: false,
		price: [60, 75, 90, 120],
		locationTown: ["Town River", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall"],
		weather: ["Rain"],
		times: [{ start: 9, end: 26 }],
		behavior: { difficulty: 45, behavior: "smooth" },
		size: { min: 20, max: 49 },
		tool: "Fishing Pole",
		baseXP: 18,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Lingcod",
		id: 45,
		desc: "A fearsome predator that will eat almost anything it can cram into its mouth.",
		type: "Regular",
		legend: false,
		price: [120, 150, 180, 240],
		locationTown: ["Mountain Lake", "Town River", "Forrest River"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 85, behavior: "mixed" },
		size: { min: 30, max: 51 },
		tool: "Fishing Pole",
		baseXP: 31,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Halibut",
		id: 46,
		desc: "A flat fish that lives on the ocean floor.",
		type: "Regular",
		legend: false,
		price: [80, 100, 120, 160],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [
			{ start: 6, end: 11 },
			{ start: 19, end: 2 },
		],
		behavior: { difficulty: 50, behavior: "sinker" },
		size: { min: 10, max: 34 },
		tool: "Fishing Pole",
		baseXP: 19,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Lobster",
		id: 47,
		desc: "A large ocean-dwelling crustacean with a strong tail.",
		type: "Crabpot",
		legend: false,
		price: [120, 120, 120, 120],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Crayfish",
		id: 48,
		desc: "A small freshwater relative of the lobster.",
		type: "Crabpot",
		legend: false,
		price: [75, 75, 75, 75],
		locationTown: [
			"Mountain Lake",
			"Town River",
			"Forrest River",
			"Forrest Pond",
		],
		locationSpecial: ["Secret Woods Pond"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Crab",
		id: 49,
		desc: "A marine crustacean with two powerful pincers.",
		type: "Crabpot",
		legend: false,
		price: [100, 100, 100, 100],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Cockle",
		id: 50,
		desc: "A common saltwater clam.",
		type: "Crabpot",
		legend: false,
		price: [50, 62, 75, 100],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Mussel",
		id: 51,
		desc: "A common bivalve that often lives in clusters.",
		type: "Crabpot",
		legend: false,
		price: [30, 37, 45, 60],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Shrimp",
		id: 52,
		desc: "A scavenger that feeds off the ocean floor. Widely prized for its meat.",
		type: "Crabpot",
		legend: false,
		price: [60, 60, 60, 60],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Snail",
		id: 53,
		desc: "A wide-ranging mollusc that lives in a spiral shell.",
		type: "Crabpot",
		legend: false,
		price: [65, 65, 65, 65],
		locationTown: [
			"Mountain Lake",
			"Town River",
			"Forrest River",
			"Forrest Pond",
		],
		locationSpecial: ["Secret Woods Pond"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Periwinkle",
		id: 54,
		desc: "A tiny freshwater snail that lives in a blue shell.",
		type: "Crabpot",
		legend: false,
		price: [20, 20, 20, 20],
		locationTown: [
			"Mountain Lake",
			"Town River",
			"Forrest River",
			"Forrest Pond",
		],
		locationSpecial: ["Secret Woods Pond"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Oyster",
		id: 55,
		desc: "Constantly filters water to find food. In the process, it removes dangerous toxins from the environment.",
		type: "Crabpot",
		legend: false,
		price: [40, 50, 60, 80],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Crabpot",
		baseXP: 5,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Woodskip",
		id: 56,
		desc: "A very sensitive fish that can only live in pools deep in the forest.",
		type: "Special",
		legend: false,
		price: [75, 93, 112, 150],
		locationTown: [],
		locationSpecial: ["Secret Woods Pond"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 50, behavior: "mixed" },
		size: { min: 11, max: 31 },
		tool: "Fishing Pole",
		baseXP: 19,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Void Salmon",
		id: 58,
		desc: "A salmon, twisted by void energy. The fresh meat is jet black, but rapidly turns pink when exposed to air.",
		type: "Special",
		legend: false,
		price: [150, 187, 225, 300],
		locationTown: [],
		locationSpecial: ["Witch Swamp"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 80, behavior: "mixed" },
		size: { min: 24, max: 66 },
		tool: "Fishing Pole",
		baseXP: 29,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Slimejack",
		id: 59,
		desc: "He's coated in a very thick layer of slime. He keeps slipping out of your hands!",
		type: "Special",
		legend: false,
		price: [100, 125, 150, 200],
		locationTown: [],
		locationSpecial: ["Mutant Bug Lair"],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 55, behavior: "dart" },
		size: { min: 8, max: 26 },
		tool: "Fishing Pole",
		baseXP: 21,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Midnight Squid",
		id: 60,
		desc: "A strange and mysterious denizen of the ocean's twilight depths.",
		type: "Special",
		legend: false,
		price: [100, 125, 150, 200],
		locationTown: [],
		locationSpecial: ["Night Market"],
		locationFarm: [],
		season: ["Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 55, behavior: "Sinker" },
		size: { min: 8, max: 25 },
		tool: "Fishing Pole",
		baseXP: 21,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Spook Fish",
		id: 61,
		desc: "The huge eyes can detect the faint silhouettes of prey.",
		type: "Special",
		legend: false,
		price: [220, 275, 330, 440],
		locationTown: [],
		locationSpecial: ["Night Market"],
		locationFarm: [],
		season: ["Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 60, behavior: "Dart" },
		size: { min: 8, max: 25 },
		tool: "Fishing Pole",
		baseXP: 23,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Blobfish",
		id: 62,
		desc: "This odd creature floats above the ocean floor, consuming any edible material in its path.",
		type: "Special",
		legend: false,
		price: [500, 625, 750, 1000],
		locationTown: [],
		locationSpecial: ["Night Market"],
		locationFarm: [],
		season: ["Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		behavior: { difficulty: 75, behavior: "Floater" },
		size: { min: 8, max: 25 },
		tool: "Fishing Pole",
		baseXP: 28,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Flounder",
		id: 63,
		desc: "It lives on the bottom, so both eyes are on top of its head.",
		type: "Regular",
		legend: false,
		price: [100, 125, 150, 200],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 20 }],
		behavior: { difficulty: 50, behavior: "sinker" },
		size: { min: 4, max: 17 },
		tool: "Fishing Pole",
		baseXP: 19,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Midnight Carp",
		id: 64,
		desc: "This shy fish only feels comfortable at night.",
		type: "Regular",
		legend: false,
		price: [150, 187, 225, 300],
		locationTown: ["Mountain Lake", "Forrest Pond"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 22, end: 26 }],
		behavior: { difficulty: 55, behavior: "mixed" },
		size: { min: 12, max: 53 },
		tool: "Fishing Pole",
		baseXP: 21,
		fishPond: true,
		cooking: true,
	},
	{
		name: "Clam",
		id: 65,
		desc: "",
		type: "Forage",
		legend: false,
		price: [50, 62, 75, 100],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Forage",
		baseXP: 5,
		fishPond: false,
		cooking: false,
	},
	{
		name: "Coral",
		id: 66,
		desc: "",
		type: "Forage",
		legend: false,
		price: [80, 100, 120, 160],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Forage",
		baseXP: 5,
		fishPond: true,
		cooking: false,
	},
	{
		name: "Sea Urchin",
		id: 67,
		desc: "",
		type: "Forage",
		legend: false,
		price: [160, 200, 240, 320],
		locationTown: ["Ocean"],
		locationSpecial: [],
		locationFarm: [],
		season: ["Spring", "Summer", "Fall", "Winter"],
		weather: ["Sun", "Wind", "Rain", "Snow"],
		times: [{ start: 6, end: 26 }],
		tool: "Forage",
		baseXP: 5,
		fishPond: true,
		cooking: false,
	},
];
exports.fish = fish;

const crops = [
	{
		name: "Blue Jazz",
		seeds: "Jazz Seeds",
		color: "#00b7c8",
		season: ["Spring"],
		growTime: 7,
		regrow: false,
		trellis: false,
		buy: { Pierre: 30, JojaMart: 37 },
		sell: 50,
		giant: false,
	},
	{
		name: "Cauliflower",
		seeds: "Cauliflower Seeds",
		color: "#cbbe93",
		season: ["Spring"],
		growTime: 12,
		regrow: false,
		trellis: false,
		buy: { Pierre: 80, JojaMart: 100 },
		sell: 175,
		giant: true,
	},
	{
		name: "Coffee Bean",
		seeds: "Coffee Bean",
		color: "#cfa036",
		season: ["Spring", "Summer"],
		growTime: 10,
		regrow: true,
		regrowTime: 2,
		trellis: false,
		buy: { "Traveling Cart": 2500 },
		sell: 15,
		giant: false,
	},
	{
		name: "Garlic",
		seeds: "Garlic Seeds",
		color: "#e5c89c",
		season: ["Spring"],
		growTime: 4,
		regrow: false,
		trellis: false,
		buy: { Pierre: 40 },
		buyNote: "Starting year 2",
		sell: 60,
		giant: false,
	},
	{
		name: "Green Bean",
		seeds: "Bean Starter",
		color: "#6cda6b",
		season: ["Spring"],
		growTime: 10,
		regrow: true,
		regrowTime: 3,
		trellis: true,
		buy: { Pierre: 60, JojaMart: 75 },
		sell: 40,
		giant: false,
	},
	{
		name: "Kale",
		seeds: "Kale Seeds",
		color: "#5e7b31",
		season: ["Spring"],
		growTime: 6,
		regrow: false,
		trellis: false,
		buy: { Pierre: 70, JojaMart: 87 },
		sell: 110,
		giant: false,
	},
	{
		name: "Parsnip",
		seeds: "Parsnip Seeds",
		color: "#fcf029",
		season: ["Spring"],
		growTime: 4,
		regrow: false,
		trellis: false,
		buy: { Pierre: 20, JojaMart: 25 },
		sell: 35,
		giant: false,
	},
	{
		name: "Potato",
		seeds: "Potato Seeds",
		color: "#dcac6d",
		season: ["Spring"],
		growTime: 6,
		regrow: false,
		trellis: false,
		buy: { Pierre: 50, JojaMart: 62 },
		sell: 80,
		giant: false,
	},
	{
		name: "Rhubarb",
		seeds: "Rhubarb Seeds",
		color: "#b30000",
		season: ["Spring"],
		growTime: 13,
		regrow: false,
		trellis: false,
		buy: { Oasis: 100 },
		sell: 220,
		giant: false,
	},
	{
		name: "Strawberry",
		seeds: "Strawberry Seeds",
		color: "#c0321b",
		season: ["Spring"],
		growTime: 8,
		regrow: true,
		regrowTime: 4,
		trellis: false,
		buy: { "Egg Festival": 100 },
		sell: 120,
		giant: false,
	},
	{
		name: "Tulip",
		seeds: "Tulip Bulb",
		color: "#fc8fa8",
		season: ["Spring"],
		growTime: 6,
		regrow: false,
		trellis: false,
		buy: { Pierre: 20, JojaMart: 25 },
		sell: 30,
		giant: false,
	},
	{
		name: "Unmilled Rice",
		seeds: "Rice Shoot",
		color: "#ce7b20",
		season: ["Spring"],
		growTime: 8,
		regrow: false,
		trellis: false,
		buy: { Pierre: 40 },
		sell: 30,
		giant: false,
	},
	{
		name: "Blueberry",
		seeds: "Blueberry Seeds",
		color: "#4d67a4",
		season: ["Summer"],
		growTime: 13,
		regrow: true,
		regrowTime: 4,
		trellis: false,
		buy: { Pierre: 80 },
		sell: 50,
		giant: false,
	},
	{
		name: "Corn",
		seeds: "Corn Seeds",
		color: "#e4c500",
		season: ["Summer", "Fall"],
		growTime: 14,
		regrow: true,
		regrowTime: 4,
		trellis: false,
		buy: { Pierre: 150, JojaMart: 187 },
		sell: 50,
		giant: false,
	},
	{
		name: "Hops",
		seeds: "Hops Starter",
		color: "#154923",
		season: ["Summer"],
		growTime: 11,
		regrow: true,
		regrowTime: 1,
		trellis: true,
		buy: { Pierre: 60, JojaMart: 75 },
		sell: 25,
		giant: false,
	},
	{
		name: "Hot Pepper",
		seeds: "Pepper Seeds",
		color: "#a85f1a",
		season: ["Summer"],
		growTime: 5,
		regrow: true,
		regrowTime: 3,
		trellis: false,
		buy: { Pierre: 40, JojaMart: 50 },
		sell: 40,
		giant: false,
	},
	{
		name: "Melon",
		seeds: "Melon Seeds",
		color: "#fe9493",
		season: ["Summer"],
		growTime: 12,
		regrow: false,
		trellis: false,
		buy: { Pierre: 80, JojaMart: 100 },
		sell: 250,
		giant: true,
	},
	{
		name: "Poppy",
		seeds: "Poppy Seeds",
		color: "#b40c18",
		season: ["Summer"],
		growTime: 7,
		regrow: false,
		trellis: false,
		buy: { Pierre: 100, JojaMart: 125 },
		sell: 140,
		giant: false,
	},
	{
		name: "Radish",
		seeds: "Radish Seeds",
		color: "#a20101",
		season: ["Summer"],
		growTime: 6,
		regrow: false,
		trellis: false,
		buy: { Pierre: 40, JojaMart: 50 },
		sell: 90,
		giant: false,
	},
	{
		name: "Red Cabbage",
		seeds: "Red Cabbage Seeds",
		color: "#d900ce",
		season: ["Summer"],
		growTime: 9,
		regrow: false,
		trellis: false,
		buy: { Pierre: 100 },
		buyNote: "Starting year 2",
		sell: 260,
		giant: false,
	},
	{
		name: "Starfruit",
		seeds: "Starfruit Seeds",
		color: "#fdfe1b",
		season: ["Summer"],
		growTime: 13,
		regrow: false,
		trellis: false,
		buy: { Oasis: 400 },
		sell: 750,
		giant: false,
	},
	{
		name: "Summer Spangle",
		seeds: "Spangle Seeds",
		color: "#90668c",
		season: ["Summer"],
		growTime: 8,
		regrow: false,
		trellis: false,
		buy: { Pierre: 50, JojaMart: 62 },
		sell: 90,
		giant: false,
	},
	{
		name: "Sunflower",
		seeds: "Sunflower Seeds",
		color: "#a44310",
		season: ["Summer"],
		growTime: 8,
		regrow: false,
		trellis: false,
		buy: { Pierre: 200, JojaMart: 125 },
		sell: 80,
		giant: false,
	},
	{
		name: "Tomato",
		seeds: "Tomato Seeds",
		color: "#a80000",
		season: ["Summer"],
		growTime: 11,
		regrow: true,
		regrowTime: 4,
		trellis: false,
		buy: { Pierre: 50, JojaMart: 62 },
		sell: 60,
		giant: false,
	},
	{
		name: "Wheat",
		seeds: "Wheat Seeds",
		color: "#f1d03a",
		season: ["Summer"],
		growTime: 4,
		regrow: false,
		trellis: false,
		buy: { Pierre: 10, JojaMart: 12 },
		sell: 25,
		giant: false,
	},
	{
		name: "Amaranth",
		seeds: "Amaranth Seeds",
		color: "#91088a",
		season: ["Fall"],
		growTime: 7,
		regrow: false,
		trellis: false,
		buy: { Pierre: 70, JojaMart: 87 },
		sell: 150,
		giant: false,
	},
	{
		name: "Artichoke",
		seeds: "Artichoke Seeds",
		color: "#5e7a31",
		season: ["Fall"],
		growTime: 8,
		regrow: false,
		trellis: false,
		buy: { Pierre: 30 },
		buyNote: "Starting year 2",
		sell: 160,
		giant: false,
	},
	{
		name: "Beet",
		seeds: "Beet Seeds",
		color: "#8b1e16",
		season: ["Fall"],
		growTime: 6,
		regrow: false,
		trellis: false,
		buy: { Oasis: 20 },
		sell: 100,
		giant: false,
	},
	{
		name: "Bok Choy",
		seeds: "Bok Choy Seeds",
		color: "#6cda6c",
		season: ["Fall"],
		growTime: 4,
		regrow: false,
		trellis: false,
		buy: { Pierre: 50, JojaMart: 62 },
		sell: 80,
		giant: false,
	},
	{
		name: "Cranberries",
		seeds: "Cranberry Seeds",
		color: "#be321b",
		season: ["Fall"],
		growTime: 7,
		regrow: true,
		regrowTime: 5,
		trellis: false,
		buy: { Pierre: 240, JojaMart: 300 },
		sell: 75,
		giant: false,
	},
	{
		name: "Eggplant",
		seeds: "Eggplant Seeds",
		color: "#9355b0",
		season: ["Fall"],
		growTime: 5,
		regrow: true,
		regrowTime: 5,
		trellis: false,
		buy: { Pierre: 20, JojaMart: 25 },
		sell: 60,
		giant: false,
	},
	{
		name: "Fairy Rose",
		seeds: "Fairy Seeds",
		color: "#cc75c4",
		season: ["Fall"],
		growTime: 12,
		regrow: false,
		trellis: false,
		buy: { Pierre: 200, JojaMart: 250 },
		sell: 290,
		giant: false,
	},
	{
		name: "Grape",
		seeds: "Grape Starter",
		color: "#781896",
		season: ["Fall"],
		growTime: 10,
		regrow: true,
		regrowTime: 3,
		trellis: true,
		buy: { Pierre: 60, JojaMart: 75 },
		sell: 80,
		giant: false,
	},
	{
		name: "Pumpkin",
		seeds: "Pumpkin Seeds",
		color: "#d55f10",
		season: ["Fall"],
		growTime: 13,
		regrow: false,
		trellis: false,
		buy: { Pierre: 100, JojaMart: 125 },
		sell: 320,
		giant: true,
	},
	{
		name: "Yam",
		seeds: "Yam Seeds",
		color: "#c2640c",
		season: ["Fall"],
		growTime: 10,
		regrow: false,
		trellis: false,
		buy: { Pierre: 60, JojaMart: 75 },
		sell: 160,
		giant: false,
	},
	{
		name: "Ancient Fruit",
		seeds: "Ancient Seeds",
		color: "#00b3c6",
		season: ["Spring", "Summer", "Fall"],
		growTime: 28,
		regrow: true,
		regrowTime: 7,
		trellis: false,
		buy: { "Traveling Cart": 1000 },
		sell: 550,
		giant: false,
	},
	{
		name: "Sweet Gem Berry",
		seeds: "Rare Seed",
		color: "#ae0000",
		season: ["Fall"],
		growTime: 24,
		regrow: false,
		trellis: false,
		buy: { "Traveling Cart": 1000 },
		sell: 3000,
		giant: false,
	},
	{
		name: "Tea Leaves",
		seeds: "Tea Sapling",
		color: "#1d8004",
		season: ["Spring", "Summer", "Fall"],
		growTime: 20,
		regrow: true,
		regrowTime: 1,
		trellis: false,
		buy: {},
		sell: 50,
		giant: false,
	},
];
exports.crops = crops;
